# SITE CONFIGURATION
baseurl: "/ncresearch"
url: "https://ncsoft.github.io"

# THEME-SPECIFIC CONFIGURATION
title: 　                                 # site's title
description: "NC Research"      # used by search engines
avatar: assets/img/renewal/text_logo_black.svg                         # Empty for no avatar in navbar
avatar2: assets/img/renewal/text_logo_white.png
favicon: assets/img/renewal/favicon.png                             # Icon displayed in the tab

# Header and footer text
header_text: "Build future values"  # Change Blog header text
header_text2: "with technology and creativity"
header_feature_image: assets/img/renewal/header.png
og_feature_image: assets/img/renewal/thumbnail.png
header_feature_image_responsive: true
footer_text: >
  Ⓒ NCSOFT Corporation. All Right Reserved.

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: default                                        # Enable mermaid-js for diagrams, use theme: base, forest, dark, default, neutral
google_analytics: G-52RLN75KFK                          # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
color_theme: light                                       # auto, dark or light

# Comments
comments:
  disqus_shortname:                                     # Your discus shortname for comments
  cusdis_app_id:                                        # Your cusdis data-app-id
  utterances:                                           # Enable by filling below information. For more info, go to https://utteranc.es
    repo:                                   # your public comments repository (e.g. owner/repo)
    issue-term:                                      # Issue term (e.g. "comment" consider issues with this word in the title as comments)

# PAGINATION
paginate: 10
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed, jekyll-sitemap, jekyll-toc]
exclude: [".jekyll-cache", ".jekyll-metadata", ".idea", "vendor/*", "assets/node_modules/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
